services:
  - type: worker
    name: japaratinga-monitor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python monitor.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    plan: free
